<start>             ::= <statement>

<statement>         ::= <command>
                      | <pipeline>
                      | <assignment>

<command>           ::= <word> <argument_list>? <redirection_list>?

<argument_list>     ::= <word>*

<redirection_list>  ::= <redirection>*

<redirection>		::=  '>' <word>
					  |  '<' <word>
					  |  <number> '>' <word>
					  |  <number> '<' <word>
					  |  '>>' <word>
					  |  <number> '>>' <word>
					  |  '<<' <word>
					  |  <number> '<<' <word>
					  |  '<&' <number>
					  |  <number> '<&' <number>
					  |  '>&' <number>
					  |  <number> '>&' <number>
					  |  '<&' <word>
					  |  <number> '<&' <word>
					  |  '>&' <word>
					  |  <number> '>&' <word>
					  |  '<<-' <word>
					  |  <number> '<<-' <word>
					  |  '>&' '-'
					  |  <number> '>&' '-'
					  |  '<&' '-'
					  |  <number> '<&' '-'
					  |  '&>' <word>
					  |  <number> '<>' <word>
					  |  '<>' <word>
					  |  '>|' <word>
					  |  <number> '>|' <word>

<assignment>        ::= <identifier> '=' <word>

<pipeline>          ::= <command> ('|' <command>)+

<name>              ::= <identifier>

<word>              ::= <identifier>
                      | <quoted_string>
                      | <double_quoted_string>

<identifier>        ::= [a-zA-Z0-9_]+

<quoted_string>     ::= "'" <single_quoted_content> "'"

<single_quoted_content> ::= ([^'])* 

<double_quoted_string> ::= '"' <double_quoted_content> '"'

<double_quoted_content> ::= ([^"])*
