<start>             ::= <statement>

<statement>         ::= <command>
                      | <pipeline>
					  | <subshell>

<command>           ::= <word> <argument_list>? <redirection_list>?

<argument_list>     ::= <word>*

<redirection_list>  ::= <redirection>*

<redirection>		::=  '>' <word>
					  |  '<' <word>
					  |  '>>' <word>
					  |  '<<' <word>

<pipeline>          ::= <command> ('|' <command>)+

<subshell>			::= <redirection_list>? '(' <statement> ')' <redirection_list>?

<name>              ::= <identifier>

<word>              ::= <identifier>
                      | <quoted_string>
                      | <double_quoted_string>

<identifier>        ::= [a-zA-Z0-9_]+

<quoted_string>     ::= "'" <single_quoted_content> "'"

<single_quoted_content> ::= ([^'])* 

<double_quoted_string> ::= '"' <double_quoted_content> '"'

<double_quoted_content> ::= ([^"])*
